# Generated by Django 5.2 on 2025-09-21 21:23

import bursary.models
import bursary.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary.county')),
            ],
            options={
                'ordering': ['county__name', 'name'],
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bursary_type', models.CharField(choices=[('county', 'County'), ('constituency', 'Constituency (NG-CDF)')], default='constituency', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='officer_profiles/')),
                ('phone', models.CharField(blank=True, help_text="Officer's phone number (optional)", max_length=20)),
                ('designation', models.CharField(blank=True, help_text="Position e.g. 'Clerk', 'Chairperson', etc.", max_length=50)),
                ('constituency', models.ForeignKey(blank=True, help_text='Leave blank if officer is county-level', null=True, on_delete=django.db.models.deletion.CASCADE, to='bursary.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('add_officer', 'Added Officer'), ('edit_officer', 'Edited Officer'), ('delete_officer', 'Deleted Officer'), ('review_application', 'Reviewed Application'), ('change_status', 'Changed Application Status')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bursary.officerprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding_name', models.CharField(default='BursaryFlow', max_length=255)),
                ('branding_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('is_active', models.BooleanField(default=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_profiles', to='bursary.constituency')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.county')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('nemis_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('institution', models.CharField(max_length=100)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('boarding', 'Boarding'), ('day', 'Day'), ('college', 'College'), ('university', 'University')], max_length=50)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_details', models.TextField(blank=True, null=True)),
                ('previous_bursary', models.BooleanField(default=False)),
                ('previous_bursary_details', models.TextField(blank=True, null=True)),
                ('date_registered', models.DateTimeField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=bursary.models.student_profile_pic_path)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bursary.constituency')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bursary.county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'admission_number'],
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('class_level', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='bursary.student')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('guardian_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='bursary.student')),
            ],
        ),
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('bursary_type', models.CharField(choices=[('county', 'County Bursary'), ('constituency', 'NG-CDF Constituency Bursary')], default='constituency', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bursary.constituency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='bursary.student')),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('id_copy', 'ID Copy'), ('admission_letter', 'Admission Letter'), ('fee_structure', 'Fee Structure'), ('result_slip', 'KCPE/KCSE/Result Slip'), ('death_cert', 'Death Certificate'), ('disability_cert', 'Disability Certificate'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=bursary.models.user_directory_path, validators=[bursary.validators.validate_file_extension, bursary.validators.validate_file_size])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bursary.bursaryapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='bursary.constituency')),
            ],
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.ward'),
        ),
    ]
