# Generated by Django 5.2 on 2025-04-17 10:34

import bursary.models
import bursary.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='file',
            field=models.FileField(upload_to=bursary.models.user_directory_path, validators=[bursary.validators.validate_file_extension, bursary.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='bursary.constituency')),
            ],
        ),
    ]
