# Generated by Django 5.2 on 2025-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='bursary_type',
            field=models.CharField(choices=[('County', 'County'), ('Constituency', 'Constituency')], default='Constituency', max_length=50),
        ),
    ]
