# Generated by Django 5.2 on 2025-04-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_alter_supportingdocument_file_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.ward'),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='constituency',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='bursary.constituency'),
            preserve_default=False,
        ),
    ]
