# Generated by Django 5.2 on 2026-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_create_default_siteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
