# Generated by Django 5.2 on 2025-04-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_bursaryapplication_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.constituency'),
        ),
    ]
