# Generated by Django 5.2 on 2026-05-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_siteprofile_slug'),
        ('bursary', '0004_bootstrap_siteprofile'),
    ]

    operations = [
    ]
