# Generated by Django 5.2 on 2025-09-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0004_supportrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportrequest',
            options={},
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='officer_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary.student'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
