# Generated by Django 5.2 on 2025-04-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0004_student_constituency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='constituency_name',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.constituency'),
        ),
    ]
