# Generated by Django 5.2 on 2025-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0005_remove_siteprofile_constituency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='constituency_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
