# Generated by Django 5.2 on 2025-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0005_alter_supportrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='viewed_by_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officeractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('add_officer', 'Added Officer'), ('edit_officer', 'Edited Officer'), ('delete_officer', 'Deleted Officer'), ('review_application', 'Reviewed Application'), ('change_status', 'Changed Application Status'), ('resolve_support_request', 'Resolved Support Request')], max_length=50),
        ),
    ]
