# Generated by Django 5.2 on 2025-04-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0006_siteprofile_constituency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='constituency_name',
        ),
    ]
