# Generated by Django 5.2 on 2025-10-04 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0006_supportrequest_viewed_by_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplication',
            name='bursary_type',
            field=models.CharField(choices=[('county', 'County Bursary'), ('constituency', 'NG-CDF Constituency Bursary')], db_index=True, default='constituency', max_length=20),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='bursary.county'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='officeractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('add_officer', 'Added Officer'), ('edit_officer', 'Edited Officer'), ('delete_officer', 'Deleted Officer'), ('review_application', 'Reviewed Application'), ('change_status', 'Changed Application Status'), ('resolve_support_request', 'Resolved Support Request')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='officeractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='bursary_type',
            field=models.CharField(choices=[('county', 'County'), ('constituency', 'Constituency (NG-CDF)')], db_index=True, default='constituency', max_length=20),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('boarding', 'Boarding'), ('day', 'Day'), ('college', 'College'), ('university', 'University')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='document_type',
            field=models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('id_copy', 'ID Copy'), ('admission_letter', 'Admission Letter'), ('fee_structure', 'Fee Structure'), ('result_slip', 'KCPE/KCSE/Result Slip'), ('death_cert', 'Death Certificate'), ('disability_cert', 'Disability Certificate'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='bursary.student'),
        ),
    ]
