# Generated by Django 5.2 on 2025-04-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0007_remove_siteprofile_constituency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplication',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bursary.constituency'),
        ),
    ]
