# Generated by Django 5.2 on 2025-04-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0008_alter_bursaryapplication_constituency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'ordering': ['county__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_profiles', to='bursary.constituency'),
        ),
        migrations.AlterField(
            model_name='student',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bursary.constituency'),
        ),
        migrations.AlterUniqueTogether(
            name='constituency',
            unique_together={('name', 'county')},
        ),
    ]
