# Generated by Django 5.2 on 2025-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0009_alter_constituency_options_alter_county_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
