# Generated by Django 5.2 on 2025-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0009_landingcontent_delete_landingshowcase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingcontent',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='landingcontent',
            name='button_link',
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='content_type',
            field=models.CharField(choices=[('slide', 'Slide'), ('showcase', 'Showcase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
