# Generated by Django 5.2 on 2025-04-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0010_student_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
