# Generated by Django 5.2 on 2025-04-20 17:35

import bursary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0011_student_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=bursary.models.student_profile_pic_path),
        ),
    ]
