# Generated by Django 5.2.7 on 2025-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bursary", "0011_landingslide_successstory_delete_landingcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officerprofile",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
