# Generated by Django 5.2 on 2025-06-10 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0012_student_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='amount_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='designation',
            field=models.CharField(blank=True, help_text="Position e.g. 'Clerk', 'Chairperson', etc.", max_length=50),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='phone',
            field=models.CharField(blank=True, help_text="Officer's phone number (optional)", max_length=20),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='officer_profiles/'),
        ),
        migrations.CreateModel(
            name='OfficerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('add_officer', 'Added Officer'), ('edit_officer', 'Edited Officer'), ('delete_officer', 'Deleted Officer'), ('review_application', 'Reviewed Application'), ('change_status', 'Changed Application Status')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
