# Generated by Django 5.2 on 2025-11-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0013_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='site_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='bursary.siteprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='site_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bursary.siteprofile'),
        ),
    ]
