# Generated by Django 5.2 on 2025-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0013_bursaryapplication_amount_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
