# Generated by Django 5.2 on 2025-12-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0014_officerprofile_site_profile_student_site_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingslide',
            name='site_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='bursary.siteprofile'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='site_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to='bursary.siteprofile'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('is_active', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False, help_text='Pin at top of list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.officerprofile')),
                ('site_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='bursary.siteprofile')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='bursary.siteprofile')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
    ]
