# Generated by Django 5.2 on 2025-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0014_officerprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_bursary_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
