# Generated by Django 5.2 on 2025-12-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0015_landingslide_site_profile_successstory_site_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='can_manage_content',
            field=models.BooleanField(default=False, help_text='Grant permission to manage slides, stories, banners, and branding'),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Manager who created this officer', limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers_created', to='bursary.officerprofile'),
        ),
    ]
