# Generated by Django 5.2 on 2025-06-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0015_student_previous_bursary_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
