# Generated by Django 5.2 on 2025-06-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0016_alter_officerprofile_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='designation',
            field=models.CharField(blank=True, help_text="Position e.g. 'Clerk', 'Chairperson', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='phone',
            field=models.CharField(blank=True, help_text="Officer's phone number (optional)", max_length=20),
        ),
    ]
