# Generated by Django 5.2 on 2025-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0017_alter_officerprofile_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='id_number',
            new_name='guardian_id_number',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='phone',
            new_name='guardian_phone',
        ),
    ]
