# Generated by Django 5.2 on 2025-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0018_rename_id_number_guardian_guardian_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='document_type',
            field=models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('id_copy', 'ID Copy'), ('admission_letter', 'Admission Letter'), ('fee_structure', 'Fee Structure'), ('result_slip', 'KCPE/KCSE/Result Slip'), ('death_cert', 'Death Certificate'), ('disability_cert', 'Disability Certificate'), ('other', 'Other')], max_length=50),
        ),
    ]
